<?php

namespace Seam\Objects;

class PhoneProperties
{
    
    public static function from_json(mixed $json): PhoneProperties|null
    {
        if (!$json) {
            return null;
        }
        return new self(
            online: $json->online,
            name: $json->name,
            model: PhoneModel::from_json($json->model),
            has_direct_power: $json->has_direct_power ?? null,
            battery_level: $json->battery_level ?? null,
            battery: isset($json->battery) ? PhoneBattery::from_json($json->battery) : null,
            manufacturer: $json->manufacturer ?? null,
            image_url: $json->image_url ?? null,
            image_alt_text: $json->image_alt_text ?? null,
            serial_number: $json->serial_number ?? null,
            online_access_codes_enabled: $json->online_access_codes_enabled ?? null,
            offline_access_codes_enabled: $json->offline_access_codes_enabled ?? null,
            supports_accessory_keypad: $json->supports_accessory_keypad ?? null,
            supports_offline_access_codes: $json->supports_offline_access_codes ?? null,
            august_metadata: isset($json->august_metadata) ? PhoneAugustMetadata::from_json($json->august_metadata) : null,
            avigilon_alta_metadata: isset($json->avigilon_alta_metadata) ? PhoneAvigilonAltaMetadata::from_json($json->avigilon_alta_metadata) : null,
            schlage_metadata: isset($json->schlage_metadata) ? PhoneSchlageMetadata::from_json($json->schlage_metadata) : null,
            smartthings_metadata: isset($json->smartthings_metadata) ? PhoneSmartthingsMetadata::from_json($json->smartthings_metadata) : null,
            lockly_metadata: isset($json->lockly_metadata) ? PhoneLocklyMetadata::from_json($json->lockly_metadata) : null,
            nuki_metadata: isset($json->nuki_metadata) ? PhoneNukiMetadata::from_json($json->nuki_metadata) : null,
            kwikset_metadata: isset($json->kwikset_metadata) ? PhoneKwiksetMetadata::from_json($json->kwikset_metadata) : null,
            salto_metadata: isset($json->salto_metadata) ? PhoneSaltoMetadata::from_json($json->salto_metadata) : null,
            genie_metadata: isset($json->genie_metadata) ? PhoneGenieMetadata::from_json($json->genie_metadata) : null,
            brivo_metadata: isset($json->brivo_metadata) ? PhoneBrivoMetadata::from_json($json->brivo_metadata) : null,
            igloo_metadata: isset($json->igloo_metadata) ? PhoneIglooMetadata::from_json($json->igloo_metadata) : null,
            noiseaware_metadata: isset($json->noiseaware_metadata) ? PhoneNoiseawareMetadata::from_json($json->noiseaware_metadata) : null,
            minut_metadata: isset($json->minut_metadata) ? PhoneMinutMetadata::from_json($json->minut_metadata) : null,
            four_suites_metadata: isset($json->four_suites_metadata) ? PhoneFourSuitesMetadata::from_json($json->four_suites_metadata) : null,
            two_n_metadata: isset($json->two_n_metadata) ? PhoneTwoNMetadata::from_json($json->two_n_metadata) : null,
            controlbyweb_metadata: isset($json->controlbyweb_metadata) ? PhoneControlbywebMetadata::from_json($json->controlbyweb_metadata) : null,
            ttlock_metadata: isset($json->ttlock_metadata) ? PhoneTtlockMetadata::from_json($json->ttlock_metadata) : null,
            seam_bridge_metadata: isset($json->seam_bridge_metadata) ? PhoneSeamBridgeMetadata::from_json($json->seam_bridge_metadata) : null,
            igloohome_metadata: isset($json->igloohome_metadata) ? PhoneIgloohomeMetadata::from_json($json->igloohome_metadata) : null,
            nest_metadata: isset($json->nest_metadata) ? PhoneNestMetadata::from_json($json->nest_metadata) : null,
            ecobee_metadata: isset($json->ecobee_metadata) ? PhoneEcobeeMetadata::from_json($json->ecobee_metadata) : null,
            hubitat_metadata: isset($json->hubitat_metadata) ? PhoneHubitatMetadata::from_json($json->hubitat_metadata) : null,
            dormakaba_oracode_metadata: isset($json->dormakaba_oracode_metadata) ? PhoneDormakabaOracodeMetadata::from_json($json->dormakaba_oracode_metadata) : null,
            wyze_metadata: isset($json->wyze_metadata) ? PhoneWyzeMetadata::from_json($json->wyze_metadata) : null,
            code_constraints: array_map(
          fn ($c) => PhoneCodeConstraints::from_json($c),
          $json->code_constraints ?? []
        ),
            supported_code_lengths: $json->supported_code_lengths ?? null,
            max_active_codes_supported: $json->max_active_codes_supported ?? null,
            supports_backup_access_code_pool: $json->supports_backup_access_code_pool ?? null,
            has_native_entry_events: $json->has_native_entry_events ?? null,
            locked: $json->locked ?? null,
            keypad_battery: isset($json->keypad_battery) ? PhoneKeypadBattery::from_json($json->keypad_battery) : null,
            door_open: $json->door_open ?? null,
            temperature_fahrenheit: $json->temperature_fahrenheit ?? null,
            temperature_celsius: $json->temperature_celsius ?? null,
            relative_humidity: $json->relative_humidity ?? null,
            can_enable_automatic_heating: $json->can_enable_automatic_heating ?? null,
            can_enable_automatic_cooling: $json->can_enable_automatic_cooling ?? null,
            available_hvac_mode_settings: $json->available_hvac_mode_settings ?? null,
            is_heating_available: $json->is_heating_available ?? null,
            is_cooling_available: $json->is_cooling_available ?? null,
            is_heating: $json->is_heating ?? null,
            is_cooling: $json->is_cooling ?? null,
            is_fan_running: $json->is_fan_running ?? null,
            fan_mode_setting: $json->fan_mode_setting ?? null,
            is_temporary_manual_override_active: $json->is_temporary_manual_override_active ?? null,
            current_climate_setting: isset($json->current_climate_setting) ? PhoneCurrentClimateSetting::from_json($json->current_climate_setting) : null,
            default_climate_setting: isset($json->default_climate_setting) ? PhoneDefaultClimateSetting::from_json($json->default_climate_setting) : null,
            is_climate_setting_schedule_active: $json->is_climate_setting_schedule_active ?? null,
            active_climate_setting_schedule: isset($json->active_climate_setting_schedule) ? PhoneActiveClimateSettingSchedule::from_json($json->active_climate_setting_schedule) : null,
            min_cooling_set_point_celsius: $json->min_cooling_set_point_celsius ?? null,
            min_cooling_set_point_fahrenheit: $json->min_cooling_set_point_fahrenheit ?? null,
            max_cooling_set_point_celsius: $json->max_cooling_set_point_celsius ?? null,
            max_cooling_set_point_fahrenheit: $json->max_cooling_set_point_fahrenheit ?? null,
            min_heating_set_point_celsius: $json->min_heating_set_point_celsius ?? null,
            min_heating_set_point_fahrenheit: $json->min_heating_set_point_fahrenheit ?? null,
            max_heating_set_point_celsius: $json->max_heating_set_point_celsius ?? null,
            max_heating_set_point_fahrenheit: $json->max_heating_set_point_fahrenheit ?? null,
            min_heating_cooling_delta_celsius: $json->min_heating_cooling_delta_celsius ?? null,
            min_heating_cooling_delta_fahrenheit: $json->min_heating_cooling_delta_fahrenheit ?? null,
            assa_abloy_credential_service_metadata: isset($json->assa_abloy_credential_service_metadata) ? PhoneAssaAbloyCredentialServiceMetadata::from_json($json->assa_abloy_credential_service_metadata) : null,
        );
    }
  

    
    public function __construct(
        public bool $online,
        public string $name,
        public PhoneModel $model,
        public bool | null $has_direct_power,
        public float | null $battery_level,
        public PhoneBattery | null $battery,
        public string | null $manufacturer,
        public string | null $image_url,
        public string | null $image_alt_text,
        public string | null $serial_number,
        public bool | null $online_access_codes_enabled,
        public bool | null $offline_access_codes_enabled,
        public bool | null $supports_accessory_keypad,
        public bool | null $supports_offline_access_codes,
        public PhoneAugustMetadata | null $august_metadata,
        public PhoneAvigilonAltaMetadata | null $avigilon_alta_metadata,
        public PhoneSchlageMetadata | null $schlage_metadata,
        public PhoneSmartthingsMetadata | null $smartthings_metadata,
        public PhoneLocklyMetadata | null $lockly_metadata,
        public PhoneNukiMetadata | null $nuki_metadata,
        public PhoneKwiksetMetadata | null $kwikset_metadata,
        public PhoneSaltoMetadata | null $salto_metadata,
        public PhoneGenieMetadata | null $genie_metadata,
        public PhoneBrivoMetadata | null $brivo_metadata,
        public PhoneIglooMetadata | null $igloo_metadata,
        public PhoneNoiseawareMetadata | null $noiseaware_metadata,
        public PhoneMinutMetadata | null $minut_metadata,
        public PhoneFourSuitesMetadata | null $four_suites_metadata,
        public PhoneTwoNMetadata | null $two_n_metadata,
        public PhoneControlbywebMetadata | null $controlbyweb_metadata,
        public PhoneTtlockMetadata | null $ttlock_metadata,
        public PhoneSeamBridgeMetadata | null $seam_bridge_metadata,
        public PhoneIgloohomeMetadata | null $igloohome_metadata,
        public PhoneNestMetadata | null $nest_metadata,
        public PhoneEcobeeMetadata | null $ecobee_metadata,
        public PhoneHubitatMetadata | null $hubitat_metadata,
        public PhoneDormakabaOracodeMetadata | null $dormakaba_oracode_metadata,
        public PhoneWyzeMetadata | null $wyze_metadata,
        public array | null $code_constraints,
        public array | null $supported_code_lengths,
        public float | null $max_active_codes_supported,
        public bool | null $supports_backup_access_code_pool,
        public bool | null $has_native_entry_events,
        public bool | null $locked,
        public PhoneKeypadBattery | null $keypad_battery,
        public bool | null $door_open,
        public float | null $temperature_fahrenheit,
        public float | null $temperature_celsius,
        public float | null $relative_humidity,
        public bool | null $can_enable_automatic_heating,
        public bool | null $can_enable_automatic_cooling,
        public array | null $available_hvac_mode_settings,
        public bool | null $is_heating_available,
        public bool | null $is_cooling_available,
        public bool | null $is_heating,
        public bool | null $is_cooling,
        public bool | null $is_fan_running,
        public string | null $fan_mode_setting,
        public bool | null $is_temporary_manual_override_active,
        public PhoneCurrentClimateSetting | null $current_climate_setting,
        public PhoneDefaultClimateSetting | null $default_climate_setting,
        public bool | null $is_climate_setting_schedule_active,
        public PhoneActiveClimateSettingSchedule | null $active_climate_setting_schedule,
        public float | null $min_cooling_set_point_celsius,
        public float | null $min_cooling_set_point_fahrenheit,
        public float | null $max_cooling_set_point_celsius,
        public float | null $max_cooling_set_point_fahrenheit,
        public float | null $min_heating_set_point_celsius,
        public float | null $min_heating_set_point_fahrenheit,
        public float | null $max_heating_set_point_celsius,
        public float | null $max_heating_set_point_fahrenheit,
        public float | null $min_heating_cooling_delta_celsius,
        public float | null $min_heating_cooling_delta_fahrenheit,
        public PhoneAssaAbloyCredentialServiceMetadata | null $assa_abloy_credential_service_metadata,
    ) {
    }
  
}
